# Basic set up for three package managers

version: 2

registries:
  composer-nativephp-composer-sh:
    type: composer-repository
    url: https://nativephp.composer.sh
    username: ${{secrets.NATIVEPHP_USERNAME}}
    password: ${{secrets.NATIVEPHP_PASSWORD}}

updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      actions-deps:
        patterns:
          - "*"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      actions-deps:
        patterns:
          - "*"

  # Maintain dependencies for Composer
  - package-ecosystem: "composer"
    directory: "/"
    registries:
      - composer-nativephp-composer-sh
    schedule:
      interval: "daily"
    groups:
      actions-deps:
        patterns:
          - "*"
